# Generated by Django 4.2.2 on 2023-07-10 09:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated_df_sample', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('c', 'Completed'), ('s', 'Skipped'), ('n', 'Not Started'), ('u', 'Needs User Input')], default='n', max_length=1)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=9000)),
                ('orcid', models.CharField(blank=True, max_length=50)),
                ('df_sample', models.JSONField(blank=True, null=True)),
                ('shape', models.JSONField()),
                ('file', models.FileField(upload_to='user_files')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('system_prompt', models.CharField(blank=True, max_length=500)),
                ('initial_assistant_message', models.CharField(blank=True, max_length=1500)),
                ('functions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=3000)),
                ('role', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('assistant', 'Assistant')], max_length=10)),
                ('gpt_response', models.JSONField(blank=True, null=True)),
                ('gpt_output_function', models.JSONField(blank=True, null=True)),
                ('df_sample', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conversation')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
    ]
