# Generated by Django 4.2.2 on 2023-07-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='task',
        ),
    ]
