# Generated by Django 5.0.2 on 2024-08-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='busy_thinking',
            field=models.BooleanField(default=False),
        ),
    ]
