# Generated by Django 5.0.2 on 2024-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataset_published_at_alter_dataset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tables',
            field=models.ManyToManyField(blank=True, null=True, to='api.table'),
        ),
    ]
