# Generated by Django 5.0.2 on 2024-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dataset_dwca_url_alter_dataset_orcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='function_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.AddField(
            model_name='message',
            name='openai_obj',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
