# Generated by Django 5.0.2 on 2024-08-20 19:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_message_content_remove_message_function_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='additional_function',
        ),
        migrations.AddField(
            model_name='task',
            name='additional_functions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), default=['test'], size=None),
            preserve_default=False,
        ),
    ]
